### PR TITLE
Add Karim Taam (matkt) as a member of Protocol Guild

### PR DESCRIPTION
**Pull request by ahamlat**
I suggest to add Karim Taam (GitHub handle: matkt), as a member of Protocol Guild. Karim was previously part of the guild but left temporarily, awaiting entity creation.

Karim has been working on Besu since July 11, 2019 https://github.com/hyperledger/besu/commits?author=matkt.

He has made substantial contributions to Bonsai, Snap sync, and numerous features in Besu. His notable achievements include the implementation of mechanisms to repair the flat database of Bonsai, which optimized block processing time. At present, he is actively working on the development of the Verkle Trie and resolving various bugs.

Karim would like to join Protocol Guild as a member but wishes to be excluded from Split V1. He wants to join the PG DAO once it is established.

### CODE REVIEW

**Review by Gabriel-Trintinalia — APPROVED** [review]

**Comment by matkt** [comment]
for verkle trie context 
https://github.com/hyperledger/besu-verkle-trie
https://github.com/matkt/besu/tree/feature/verkle-trie-integration

**Review by garyschulte — APPROVED** [review]
:shipit:

**Review by gballet — APPROVED** [review]
Yes, Karim had to leave awaiting the creation of the entity, for tax purposes in his jurisdiction. Reintegrating him is a no-brainer imo.

**Review by macfarla — APPROVED** [review]

**Review by jframe — APPROVED** [review]

**Comment by shemnon** [comment]
Per the discussion on discord can we simply nominate Karim for this list, have him nominate and have the legal entity represent him on the backend, and remove the reference to devrim in the member list?  Or is it critical devrim be listed?

**Comment by matkt** [comment]
> Per the discussion on discord can we simply nominate Karim for this list, have him nominate and have the legal entity represent him on the backend, and remove the reference to devrim in the member list? Or is it critical devrim be listed?

It's good to just put karim taam

**Review by lucassaldanha — APPROVED** [review]

**Review by timbeiko — APPROVED** [review]
Strongly support this 😄

**Review by shemnon — APPROVED** [review]
+1

Also, squash commit? ;)

**Comment by ahamlat** [comment]
@tvanepps Can we merge this PR or do we have to wait for further approvals ?

**Comment by tvanepps** [comment]
> @tvanepps Can we merge this PR or do we have to wait for further approvals ?

sorry! catching up from holidays

**Pull request merged**
