### PR TITLE
Add NC to Lodestar

### PR DESCRIPTION
**Pull request by philknows**
Name: NC
Team: Lodestar
Discord Handle: nc1234
Weight: Full

## Oct 2022 - Feb 2023: EPF
- Consensus client reward APIs [overview](https://github.com/kevinbogner/cohort-three/blob/master/projects/consensus_client_reward_APIs.md)
- block_rewards and attestation_rewards in Lighthouse https://github.com/sigp/lighthouse/pull/3907
- sync_committee_rewards in Lighthouse https://github.com/sigp/lighthouse/pull/3903

## Feb 2023: Reth
- Adding test support for several API module to Reth https://github.com/paradigmxyz/reth/pull/1288

## Mar 2023 - Jul 2023: EIP-6110 prototype
- Besu implementation https://github.com/hyperledger/besu/pull/5295, https://github.com/hyperledger/besu/pull/5055
[EIP-6110 PEEPanEIP](https://www.youtube.com/watch?v=tRTBgCN9VgY)

## May 2023: Erigon
- Diagnositc and debugging endpoints https://github.com/ledgerwatch/erigon/pull/7417, https://github.com/ledgerwatch/diagnostics/pull/10

## July 2023 - Today: Lodestar
- Implement EIP-6110 in Lodestar: https://github.com/ChainSafe/lodestar/pull/6042
- Add consensus_block_value to produceBlockV3: https://github.com/ChainSafe/lodestar/pull/6136
- Add response headers to produceBlockV3: https://github.com/ChainSafe/lodestar/pull/6228
- Add endpoint for Altair block reward: https://github.com/ChainSafe/lodestar/pull/6178
- Add proposer boost: https://github.com/ChainSafe/lodestar/pull/6298
- Add endpoint for sync committee reward: https://github.com/ChainSafe/lodestar/pull/6260

### CODE REVIEW

**Review by michaelsproul — APPROVED** [review]
Having worked with NC I'm happy to attest to the quality of his work on Lighthouse

I support his inclusion in PG!

**Review by dapplion — APPROVED** [review]
I attest NC's work!

**Review by siladu — APPROVED** [review]
Can attest to Navie's work on Besu, and overall think joining PG is well deserved.

**Review by mkalinin — APPROVED** [review]
Navie did a great job prototyping eip6110, the project which I was a part of! More than happy to have him as a PG member.

**Review by tuyennhv — APPROVED** [review]

**Pull request merged**
