### PR TITLE
Add Dimitry from EF Testing

### PR DESCRIPTION
**Pull request by winsvega**
## Name
Dimitry, aka [winsvega](https://github.com/winsvega).

## Team
Testing Team @ Ethereum Foundation

## Short summary of their work / eligibility
Dimitry was one of the first ethereum employees back in 2014.  He joined ethereum aleth team (back then cpp-ethereum) and worked on testeth application that was used that time to make first evm json tests such as Blockchain and State tests .jsons. 

After aleth discontinued, the testeth app was reformed as [retesteth](https://github.com/ethereum/retesteth) and was used to maintain, develop and generate all the test vectors from [tests](https://github.com/ethereum/tests) 

Dimitry has developed and supported most of the tests from that repo among with retesteth and later t8n tool protocol that is now used to generate the tests.  

### Code
* Maintainer of [tests](github.com/ethereum/tests)
* Maintainer of [retesteth](https://github.com/ethereum/retesteth) http://retesteth.ethdevops.io/
* Pyspecs contributor [pyspecs](https://github.com/ethereum/execution-spec-tests/pulls?q=+is%3Apr+author%3Awinsvega+)
 
### Talks
[Shanghai Devcon: Testing ethereum consensus](https://archive.devcon.org/archive/watch/2/testing-ethereum-consensus/?playlist=Devcon%202)
[Cancun Devcon: Ethereum protocol testing](https://archive.devcon.org/archive/watch/3/ethereum-protocol-testing/?playlist=Devcon%203)
 
### In progress / Planned
Currently working on:
* Mastering python tests format [pyspecs prs](https://github.com/ethereum/execution-spec-tests/pulls?q=+is%3Apr+author%3Awinsvega+)
* Supporing .json/.yml test vector updates with all ethereum hard fork upgrades

Planned:
* Mastering python test format, contribute to execution-spec-tests development
* Converting existing .json/.yml tests into .py tests
* Updating existent .json/.yml tests to Cancun and beyond, untill it's converted into .py 

### Start date of relevant projects
December 1st, 2014 (EF team)
January 1st, 2024 (EF Testing team)
 
## Proposed weight (full or partial)
Full*
 
*Dimitry has 2 little kids growing up that influence his availability hours

### CODE REVIEW

**Review by lightclient — APPROVED** [review]
Obviously we all use Dimitry's tests :)

**Review by marioevz — APPROVED** [review]

**Comment by marioevz** [comment]
Dimitry is an integral part of the testing team and his tests have supported and will continue to support the Ethereum clients :+1:

**Review by SamWilsn — APPROVED** [review]

**Review by mkalinin — APPROVED** [review]

**Review by potuz — APPROVED** [review]
Love the precedent this sets of self-opening the PR and I strongly empathize with two kids affecting availability (and sleep quality in my case)

**Review by yperbasis — APPROVED** [review]

**Comment by tvanepps** [comment]
> Love the precedent this sets of self-opening the PR

adding a note that while we have discussed self-nominations in the past, currently the expectation is that only existing members are capable of new member nominations. This adds accountability to the process (eg. proposers are expected demonstate an understanding of their work, and potentially vouch for them in the future), as well as a point person to help with their onboarding (eg. sending form, explaining what PG is if needed)

We can keep this PR (i think the repo settings have been fixed now), but just writing this out for others' awareness. If for some reason i didn't fix the settings, I'll close any future self-nomination PRs and have another member make the nomination.

**Comment by tvanepps** [comment]
adding a separate comment asking for more clarity on weights throughout the contribution period

> December 1st, 2014 (EF team)
> January 1st, 2024 (EF Testing team)

The minimum expectation for PG eligibility is at least 50% time. Can you give more context about full time, part time and inactive periods (if any) over the years? for example:

dec 1st EF team
Jan 1st EF testing
X months part time
Y months inactive

This helps get the accurate number into the final % weighting and will be asked for in the onboarding form. thanks!

**Comment by tvanepps** [comment]
For the sake of long-term consistency, probably best to actually close and have @marioevz make the proposal. Sorry for going back and forth!

**Comment by winsvega** [comment]
@marioevz shall remake the proposal

**Pull request closed without merging**
