### PR TITLE
Add primary contributions of axic

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Review by tvanepps — COMMENTED** [review]
ethereum/EIPs isn't eligible under our framework, could you remove? otherwise looks good!

**Comment by axic** [comment]
> ethereum/EIPs isn't eligible under our framework, could you remove? otherwise looks good!

Wasn't clear to me, as several members have it listed. Removed.

**Comment by poojaranjan** [comment]
Ethereum protocol and network upgrades are dependent on EIPs and should be included. If Ethereum/EIPs are not yet considered under the Protocol Guild category, I propose adding them to the list.

**Comment by tvanepps** [comment]
> Ethereum protocol and network upgrades are dependent on EIPs and should be included. If Ethereum/EIPs are not yet considered under the Protocol Guild category, I propose adding them to the list.

would be a separate process to this PR, and would need a much broader discussion about the tradeoffs involved with effectively incentivizing the creation of EIPs. the bulk of the work is in finding tradeoffs/bugs, implementing, testing, maintaining longterm

**Pull request merged**
